// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClcN0RFJnM3z0zyIYjlSLLsXN3WyExXMM',
    appId: '1:523886626233:web:69de2b1b4845d8e46a2268',
    messagingSenderId: '523886626233',
    projectId: 'lpcc-library',
    authDomain: 'lpcc-library.firebaseapp.com',
    databaseURL: 'https://lpcc-library-default-rtdb.firebaseio.com',
    storageBucket: 'lpcc-library.firebasestorage.app',
    measurementId: 'G-QYWGXD9C0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtqzSSn4Y2bWSvREGPhtL3-58_vJ4JrKM',
    appId: '1:523886626233:android:4c86566bdeaeca8b6a2268',
    messagingSenderId: '523886626233',
    projectId: 'lpcc-library',
    databaseURL: 'https://lpcc-library-default-rtdb.firebaseio.com',
    storageBucket: 'lpcc-library.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmlSgPoX5P22MjvWvj682CV5--G6juZ0g',
    appId: '1:523886626233:ios:c825679617bf6d4f6a2268',
    messagingSenderId: '523886626233',
    projectId: 'lpcc-library',
    databaseURL: 'https://lpcc-library-default-rtdb.firebaseio.com',
    storageBucket: 'lpcc-library.firebasestorage.app',
    iosBundleId: 'com.lilyspadchildcare.lpccl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmlSgPoX5P22MjvWvj682CV5--G6juZ0g',
    appId: '1:523886626233:ios:c825679617bf6d4f6a2268',
    messagingSenderId: '523886626233',
    projectId: 'lpcc-library',
    databaseURL: 'https://lpcc-library-default-rtdb.firebaseio.com',
    storageBucket: 'lpcc-library.firebasestorage.app',
    iosBundleId: 'com.lilyspadchildcare.lpccl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClcN0RFJnM3z0zyIYjlSLLsXN3WyExXMM',
    appId: '1:523886626233:web:0099ae8c48434e396a2268',
    messagingSenderId: '523886626233',
    projectId: 'lpcc-library',
    authDomain: 'lpcc-library.firebaseapp.com',
    databaseURL: 'https://lpcc-library-default-rtdb.firebaseio.com',
    storageBucket: 'lpcc-library.firebasestorage.app',
    measurementId: 'G-D758CDB5V0',
  );
}
